feat: Добавили возможность бронировать вещи
VazAnton/java-shareit pull request #2
Opened 2024-04-22 15:34 UTC by VazAnton

2024-04-22 16:15 UTC, VazAnton commented
Падают 2 postman-теста в папке bookings в одном методе, не получается найти ошибку
![image](https://github.com/VazAnton/java-shareit/assets/137683045/7c17a09b-6a6c-4acc-9e4c-1eec25709327)

2024-04-23 20:19 UTC, TomattmanYandex requested changes
Привет, мне неожиданно прилетела работа на проверку, поэтому слегка задержался с проверкой

1) надо сделать так, чтобы проверки пайплайна прошли, это одно из требований
попытайся еще, если не получится, пиши либо наставнику, либо мне попытаемся разобраться вместе
2) я смотрел по большей степени на стиль кода комменты оставил в одном месте, но касаться они будут всех мест (таких много)
3) код смотрится перегруженным и тяжело читаемым, (на уровне сервисов)
я оставил комента как это можно поправить, это не обязательное требование, но настоятельно рекомендую посмотреть и поработать над этим

По поводу падающих постман тестов не подскажу, как минимум потому что у меня к ним доступа нету, а сборка до них так и не дошла, так как упали юнит тесты. С этими вопросами лучше подойти к преподавателю

Чуть что пиши в чат, но я там могу медленно отвечать

2024-04-23 20:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +@Validated
зачем тут эта аннотация, или зачем они нужны в параметрах методов

2024-04-23 20:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    Comparator<Booking> bookingDateComparator = (booking1, booking2) -> {
если это переменная стоит добавить модификатор доступа
но чаще компараторы создают отдельным классом чтобы легче было переиспользовать

2024-04-23 20:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Booking inMemoryBookingDto = entityMapper.shortBookingDtoToBooking(shortBookingDto);
вопрос по читаемости
1) если разбить на методы поменьше с понятными именами, будет читаться получше
напримервынести все валидации в другой метод, а лучше в несколько методов, и сделать например методы
validateAvialability, validateBookingDate  и т.д.
2) некоторые вещи лучше тоже вынести в отдлеьные методы, например получение обьектов из репозитория
вместо
  inMemoryBookingDto.setBooker(userRepository.findById(userId).orElseThrow(() ->
                new EntityNotFoundException("Внимание! Пользователя с таким номером не существует!")));

сделать 
inMemoryBookingDto.setBooker(getUserById(userId));

и отдельный метод
private User getUserById(long id){
  return userRepository.findById(userId).orElseThrow(() ->
                new EntityNotFoundException("Внимание! Пользователя с таким номером не существует!"));
}
так код основного метода станет проще, а вспомогательный метод можно переиспользовать
и не будет налеплено куча кода в одно месте

2024-04-23 20:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        } else if (inMemoryBookingDto.getEnd().isBefore(inMemoryBookingDto.getStart())) {
так как у тебя в блоке if пробрасывается исключение
то если он выполнится то до блока else выполнение уже не дойдет, и следовательно else уже не обязательно 

А читаться будет лучше

2024-04-23 20:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        } else if (inMemoryBookingDto.getEnd().isBefore(inMemoryBookingDto.getStart())) {
то же самое и ниже будет с return
он будет работать так же

2024-04-23 20:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        } else if (inMemoryBookingDto.getEnd().isBefore(inMemoryBookingDto.getStart())) {
if(true) {
  throw new Exception();
}
//еслb код дойдет сюда, то значит первое условие не выполнилось

2024-04-23 20:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        } else if (inMemoryBookingDto.getEnd().isBefore(inMemoryBookingDto.getStart())) {
if(true) {
   throw new Exception();
}
if(true) {
   throw new Exception();
}
if(true) {
   throw new Exception();
}

читается лучше чем если использовать else if

2024-04-23 20:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (State.valueOf(state).equals(State.WAITING)) {
Тут лучше бы подошло switch case

2024-04-23 20:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +//            if (bookingRepository.findAll().isEmpty() /*||
Закомментированный код не допускается

2024-04-23 20:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/mappers/EntityMapper.java
> +public interface EntityMapper {
лучше иметь несколько классов мапперов, и завязаться например на обьект базы, чем один универсальный на все 

это для того, чтобы если ты изменишь маппинг например только букинга, то тебе надо будет изменить маппер только букинга, и не трогать маппер для пользователей, а раз ты не трогаешь класс, значит шанс что ты добавишь туда проблем гораздо меньше

2024-04-23 20:19 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/item/ItemRepositoryWithoutBdTest.java
> +//package ru.practicum.shareit.item;
закомментированный код не допускается

2024-04-26 15:51 UTC, VazAnton commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +@Validated
Применяю её в методе addBooking для проверки приходящего ShortBookingDto

2024-04-27 16:58 UTC, TomattmanYandex approved these changes
Привет, так как работа проходит все тесты, и критических ошибок нету, то не могу не принять, но комментарии которые я оставлял раньше, важны для написания качественного кода, и поэтому я бы рекомендовал пройтись еще раз по ним

2024-04-27 16:58 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +@Validated
но ты везде используешь @Valid

2024-04-29 09:02 UTC, merged