feat: Возможность оставлять запросы
VazAnton/java-shareit pull request #3
Opened 2024-05-10 12:40 UTC by VazAnton

2024-05-10 14:39 UTC, TomattmanYandex requested changes
Привет, вопросы по тестам, не хватает тестов репозитория, плюс существующие тесты стоило бы реализовать по другому, чтобы не было столько переменных на уровне тестового класса
не хватает тестов для проверки Dto, с аннотацией @JsonTest
не хватает полноценных интеграционных тестов, которые проверят взаимодействие между сервисами (эти тесты будут без моков)
не хватет конфигурации тестовой, чтобы тесты заупскались на тестовой базе данных

еще я рекомендую назвать тестовые классы чтобы было понятнее по типу
на примере букинга
BookingMockMvcTest проверяет контроллер и возвращаемые значения сервисы могут быть замоканы
BokingRepositotyTest проверяет репозиторий и метды репозитория (сейчас они ничего не проверяют)
BookingServiceIntegrationTest тест который вызывает сервис, а потом проверяет что в базе данных что то появилось, без моков (только какие то внешние сервисы)
BookingDtoTest если перевод в json содержит какую то логику (подойдет тестирование ItemRequest потому что там есть перевод дат, проверить что даты правильно преобразовываются

2024-05-10 14:39 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Page<Booking> getAllBookingsInfoByOwnerLikePage(long userId, Pageable pageable);
это можно реализовать без запроса назвав метод findByOwnerId

2024-05-10 14:39 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +public class BookingRepositoryTest {
тест есть а ничего не тестируется

2024-05-10 14:39 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    UserDto userDto;
возможно было бы лучше создавать обьекты для тестов в каждом тесте отдельно, ибо пока что это ну очень пугает, огромное количство переменных, которые могут кочевать и изменяться из одного теста в другой

вариант лучше, сделать отдельные методы на создание разных обьектов в базе, и в начале тестового метода вызвать эти методы

2024-05-11 08:10 UTC, VazAnton commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +public class BookingRepositoryTest {
Добавил тестирование для всех репозиториев

2024-05-11 08:13 UTC, VazAnton commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Page<Booking> getAllBookingsInfoByOwnerLikePage(long userId, Pageable pageable);
Так как поле owner находится не напрямую у сущности Booking, а связано с ней через сущность Item, извлечь информацию о букингах через поле ownerId, использую запросный метод не получается, поэтому пока оставил над методом QPJL-запрос

2024-05-11 09:12 UTC, VazAnton commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    UserDto userDto;
Убрал инициализацию лишних переменных перед теми тестами, в которых они не нужны, нашёл несколько переменных, вообще неиспользуемых в тестовом классе, убрал их объявление и инициализацию

2024-05-11 09:20 UTC, VazAnton commented
Привет! Проработал комментарии и прошу зачесть данную работу несмотря на то, что она не идеальна, с учетом того, что функционально всё всё таки работает и тесты покрывают необходимую часть кода.

2024-05-12 06:59 UTC, TomattmanYandex requested changes
Привет,  есть еще несколько моментов

1) не обязательный, но если сделать это сразу плюсик в карму - имена тестовых методов - лучшая структура имени, это из трех частей - название тестируемого метода_что должен делать_при каких условиях , так гораздо лучше тесты воспринимаются
2) не обязательный, все еще переменные на уровне класса в тестах, вместо того чтобы хранить на уровне класса переменную, лучше сделать метод который будет возвращать объект этого класса и использовать ее (простой пример почему так лучше, предположим есть метод который изменяет состояние объекта, в одном методе ты изменяешь значение этой переменной, в других в зависимости от реализации они уже будут работать с другими - бац, потенциальная ошибка)
3) надо исправить, нужны полноценный интеграционные тесты - это тесты без моков например с уровня сервиса или контроллера, в которых мы на урвоне сервиса делаем что-то а потом на уровне базы проверяем что обьект прошел все слои, и сделал то что надо
например добавление букинга делаем на уровне контроллера, а потом смотрим что в базе появился нужный букинг, с нужными значениями полей

2024-05-13 07:18 UTC, TomattmanYandex approved these changes
ПРинято, из дополнений, обычно не пишут сразу все типы тестов, чаще всего есть юнит тесты, и интеграционные на сервисы, тесты контроллеров часто мокают
но вообще чаще всего хватить или интеграционного на контроллер, или интеграционного с mockMvc

2024-05-13 15:50 UTC, merged